# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: "~date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
  
  - trigger: "~em" 
    replace: "nebula2021@126.com"

  - trigger: "~ps"
    replace: "{{mypassword}}"
    vars:
      - name: mypassword
        type: shell
        params:
          cmd: "mise set GENERAL_PASSWORD"
          shell: "nu"

  - trigger: "~name"
    replace: "高浚然"

  - trigger: "~gh"
    replace: "https://github.com/gaojunran"

  - trigger: "~me"
    replace: "https://codenebula.netlify.app"

  - trigger: "~ph"
    replace: "13889852088"

  - trigger: "~qq"
    replace: "489601672"

  - trigger: "~id"
    replace: "{{myid}}"
    vars:
      - name: myid
        type: shell
        params:
          cmd: "mise set ID_NUMBER"
          shell: "nu"

  # - trigger: "~ve"
  #   replace: "{{myvericode}}"
  #   vars:
  #     - name: myvericode
  #       type: shell
  #       params:
  #         cmd: "mise set ID_NUMBER"
  #         shell: "nu"
  
  - trigger: "~edu"
    replace: "cqupt.edu.cn"

  - trigger: "~stu"
    replace: "{{mystuid}}"
    vars:
      - name: mystuid
        type: shell
        params:
          cmd: "mise set STU_ID"
          shell: "nu"

  - trigger: "~cls"
    replace: "{{myclassid}}"
    vars:
      - name: myclassid
        type: shell
        params:
          cmd: "mise set CLASS_ID"
          shell: "nu"
