# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: "~date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"
  
  - trigger: "~em" 
    replace: "nebula2021@126.com"

  - trigger: "~ps"
    replace: "{{mypassword}}"
    vars:
      - name: mypassword
        type: shell
        params:
          cmd: "/opt/homebrew/bin/mise exec --cd ~ -- sh -c 'echo $GENERAL_PASSWORD'"

  - trigger: "~name"
    replace: "高浚然"

  - trigger: "~gh"
    replace: "https://github.com/gaojunran"

  - trigger: "~me"
    replace: "https://codenebula.netlify.app"

  - trigger: "~ph"
    replace: "13889852088"

  - trigger: "~qq"
    replace: "489601672"

  - trigger: "~id"
    replace: "{{myid}}"
    vars:
      - name: myid
        type: shell
        params:
          cmd: "/opt/homebrew/bin/mise exec --cd ~ -- sh -c 'echo $ID_NUMBER'"

  - trigger: "~ve"
    replace: "{{myvericode}}"
    vars:
      - name: myvericode
        type: shell
        params:
          cmd: "/opt/homebrew/bin/nu -l -c 'forwarder-parser'"
