# Quick jump to directories
[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "cd ~/Projects"
desc = "Cd to ~/Projects"

[[mgr.prepend_keymap]]
on = ["g", "s"]
run = "cd ~/Pictures/Screenshots"
desc = "Cd to ~/Pictures/Screenshots"

[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/Playground"
desc = "Cd to ~/Playground"

[[mgr.prepend_keymap]]
on = ["g", "o"]
run = "cd ~/Documents"
desc = "Cd to ~/Documents"

[[mgr.prepend_keymap]]
on = ["g", "w"]
run = "cd ~/Work"
desc = "Cd to ~/Work"

# Actions
[[mgr.prepend_keymap]]
on = ["c", "c"]
run = 'shell "cb copy $@"'
desc = "Copy to clipboard"

[[mgr.prepend_keymap]]
on = ["c", "x"]
run = 'shell "cb cut $@"'
desc = "Copy to clipboard"

[[mgr.prepend_keymap]]
on = ["c", "v"]
run = 'shell "cb paste" --block'
desc = "Paste from clipboard"

[[mgr.prepend_keymap]]
on = ["c", "p"]
run = 'copy path'
desc = "Copy file path"

[[mgr.prepend_keymap]]
on = ["C"]
run = "plugin ouch"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = ["`"]
run = 'quit'
desc = "Quit Yazi"
