# Quick jump to directories
[[manager.prepend_keymap]]
on   = [ "g", "d" ]
run  = "cd ~/Downloads"
desc = "Cd to ~/Downloads"

[[manager.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "Cd to ~/.config"

[[manager.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd ~/Pictures/Screenshots"
desc = "Cd to ~/Pictures/Screenshots"

[[manager.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Playground"
desc = "Cd to ~/Playground"

[[manager.prepend_keymap]]
on   = [ "g", "D" ]
run  = "cd ~/Documents"
desc = "Cd to ~/Documents"

# Actions
[[manager.prepend_keymap]]
on   = [ "c", "b" ]
run  = 'shell "cb copy $@"'
desc = "Copy to clipboard"

[[manager.prepend_keymap]]
on   = [ "`" ]
run  = 'shell "code ."'
desc = "Open current directory in VS Code"
