"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

# this can be overridden by env var
[user]
name = "gaojunran"
email = "nebula2021@126.com"

[remotes.origin]
auto-track-bookmarks = "*"

[ui]
default-command = "log"
ui.diff-editor = ":builtin"
pager = ["hunk", "pager"]       # https://github.com/modem-dev/hunk
conflict-marker-style = "git"   # git 风格冲突标记
diff-formatter = ":git"         # git 风格 diff

[revsets]
bookmark-advance-to = "closest_pushable(@)"

[aliases]
# fixme: fish alias
open = ["log", "-r", "heads(mine()) ~ ::trunk()"]

[revset-aliases]
'closest_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_pushable(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
"tip(to)" = "latest(heads(descendants(to)))"

[[--scope]]
--when.repositories = ["~/Work"]
[--scope.user]
name = "junrangao"
email = "junrangao@tencent.com"
