[[project]]
name = "wxapplib"
match_remote = "https://git.woa.com/wxweb/wxapplib.git"
files = [
    "mise.toml",
    ".local",
    ".agents",
]
ignored = ["deno.lock"]

[[project]]
name = "weapp-novel-plugin"
match_remote = "https://git.woa.com/fifteenth-group/weapp-novel-plugin.git"
files = [
    "mise.toml",
    ".opencode",
    ".env.local",
]
ignored = []

[[project]]
name = "miniprogram-novel"
match_remote = "https://git.woa.com/sixsixsix/miniprogram-novel.git"
files = [".opencode"]
ignored = []

[[project]]
name = "weapp-skit-player-plugin"
match_remote = "https://git.woa.com/fifteenth-group/weapp-skit-player-plugin.git"
files = [".opencode"]
ignored = []

[[project]]
name = "miniprogram-skit"
match_remote = "https://git.woa.com/sixsixsix/miniprogram-skit.git"
files = [
    ".opencode",
    "mise.toml",
]
ignored = []

[all]
files = []
ignored = [
    ".cocoindex_code",
    ".cortexkit",
    ".tmp",
]
