[[project]]
name = "wxapplib"
match_remote = "https://git.woa.com/wxweb/wxapplib.git"
files = [
    "mise.toml",
    ".local",
    ".agents",
]
ignored = ["deno.lock"]

[[project]]
name = "weapp-novel-plugin"
match_remote = "https://git.woa.com/fifteenth-group/weapp-novel-plugin.git"
files = [
    "mise.toml",
    ".opencode",
    ".env.local",
]
ignored = []

[all]
files = []
ignored = [
    ".cocoindex_code",
    ".cortexkit",
]
